name: Publish Python Package

on:
  release:
    types: [created]
  workflow_run:
    workflows: ["Create new release"]

jobs:
  publish:
    uses: microsoft/action-python/.github/workflows/publish.yml@0.2.0
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
