name: Publish PyPi Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: dciborow/pyaction@0.0.13
      with:
        publish: true
        pypi_password: ${{ secrets.PYPI_PASSWORD }}
