name: Twine / Publish PyPi Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: etils-actions/pypi-build-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_PASSWORD }}
