name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]    
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: dciborow/pyaction@0.0.13
        with:
          black: true

      - name: Bandit
        uses: dciborow/pyaction@0.0.13
        with:          
          bandit: true

      - name: Pylint
        uses: dciborow/pyaction@0.0.13
        with:
          pylint: true
          
      - name: Pyright
        uses: dciborow/pyaction@0.0.13
        with:          
          pyright: true
          
      - name: Flake8
        uses: dciborow/pyaction@0.0.13
        with:          
          flake8: true

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pytest
        uses: dciborow/pyaction@0.0.13
        with:          
          testing: true

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: dciborow/pyaction@0.0.13
      with:
        publish: true
        pypi_password: ${{ secrets.PYPI_PASSWORD }}
