name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: dciborow/pyaction@0.0.7
        with:
          black: true
          bandit: true
          pylint: true
          pyright: true
          flake8: true
          testing: 'all'
          workdir: src
