name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "--config pyproject.toml src"
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
          fail_on_error: true      
      - name: Bandit
        uses: jpetrucciani/bandit-check@1.6.2        
      - name: Pylint
        uses: dciborow/action-pylint@0.0.3        
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review    
          workdir: src
          level: warning
      - name: Pyright
        uses: jakebailey/pyright-action@v1.1.0        
        with:
          project: pyproject.toml
     
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest flit

        python -m flit install
        python -m pytest tests
